/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

package it.eng.sacerasi.grantEntity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator edited by fioravanti_f
 */
@Entity
@Table(schema = "SACER_IAM", name = "ORG_AMBIENTE_ENTE_CONVENZ")
public class SIOrgAmbienteEnteConvenz implements Serializable {

    private static final long serialVersionUID = 1L;
    private String dsAmbienteEnteConvenz;
    private Long idAmbienteEnteConvenz;
    private String nmAmbienteEnteConvenz;
    private SIOrgEnteSiam orgEnteSiamByIdEnteConserv;
    private SIOrgEnteSiam orgEnteSiamByIdEnteGestore;
    private List<SIOrgEnteSiam> orgEnteConvenzs = new ArrayList<>();

    public SIOrgAmbienteEnteConvenz() {
    }

    public SIOrgAmbienteEnteConvenz(long idAmbienteEnteConvenz) {
        this.idAmbienteEnteConvenz = idAmbienteEnteConvenz;
    }

    @Basic
    @Column(name = "DS_AMBIENTE_ENTE_CONVENZ", nullable = false, length = 254)
    public String getDsAmbienteEnteConvenz() {
        return dsAmbienteEnteConvenz;
    }

    public void setDsAmbienteEnteConvenz(String dsAmbienteEnteConvenz) {
        this.dsAmbienteEnteConvenz = dsAmbienteEnteConvenz;
    }

    @Id
    @Column(name = "ID_AMBIENTE_ENTE_CONVENZ")
    public Long getIdAmbienteEnteConvenz() {
        return idAmbienteEnteConvenz;
    }

    public void setIdAmbienteEnteConvenz(Long idAmbienteEnteConvenz) {
        this.idAmbienteEnteConvenz = idAmbienteEnteConvenz;
    }

    @Basic
    @Column(name = "NM_AMBIENTE_ENTE_CONVENZ", nullable = false, length = 100)
    public String getNmAmbienteEnteConvenz() {
        return nmAmbienteEnteConvenz;
    }

    public void setNmAmbienteEnteConvenz(String nmAmbienteEnteConvenz) {
        this.nmAmbienteEnteConvenz = nmAmbienteEnteConvenz;
    }

    // bi-directional many-to-one association to OrgEnteSiam
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_ENTE_CONSERV")
    public SIOrgEnteSiam getOrgEnteSiamByIdEnteConserv() {
        return this.orgEnteSiamByIdEnteConserv;
    }

    public void setOrgEnteSiamByIdEnteConserv(SIOrgEnteSiam orgEnteSiamByIdEnteConserv) {
        this.orgEnteSiamByIdEnteConserv = orgEnteSiamByIdEnteConserv;
    }

    // bi-directional many-to-one association to OrgEnteSiam
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_ENTE_GESTORE")
    public SIOrgEnteSiam getOrgEnteSiamByIdEnteGestore() {
        return this.orgEnteSiamByIdEnteGestore;
    }

    public void setOrgEnteSiamByIdEnteGestore(SIOrgEnteSiam orgEnteSiamByIdEnteGestore) {
        this.orgEnteSiamByIdEnteGestore = orgEnteSiamByIdEnteGestore;
    }

    @OneToMany(mappedBy = "siOrgAmbienteEnteConvenz", cascade = CascadeType.MERGE)
    public List<SIOrgEnteSiam> getOrgEnteConvenzs() {
        return orgEnteConvenzs;
    }

    public void setOrgEnteConvenzs(List<SIOrgEnteSiam> orgEnteConvenzs) {
        this.orgEnteConvenzs = orgEnteConvenzs;
    }

}
